### ISSUE TITLE
A bug in the results obtained using simple-wappalyzer

### ISSUE THREAD

**Issue by anooj-gandham** [Kikobeats/simple-wappalyzer#23]
The list of technologies obtained using simple-wappalyzer is a subset of the results obtained using wappalyzer library. 
Do I need to change any settings to get complete list of results?

URL : https://stackoverflow.com/questions/221294/how-do-you-get-a-timestamp-in-javascript

The results of simple-wappalyzer and wappalyzer are attached below:
Simple-Wappalyzer results:
[
    {
        "name": "Varnish",
        "slug": "varnish",
        "categories": [
            {
                "id": 23,
                "slug": "caching",
                "name": "Caching",
                "priority": 7
            }
        ],
        "confidence": 100,
        "version": "",
        "icon": "Varnish.svg",
        "website": "http://www.varnish-cache.org",
        "cpe": null
    },
    {
        "name": "Stimulus",
        "slug": "stimulus",
        "categories": [
            {
                "id": 12,
                "slug": "javascript-frameworks",
                "name": "JavaScript frameworks",
                "priority": 8
            }
        ],
        "confidence": 100,
        "version": "",
        "icon": "Stimulus.png",
        "website": "https://stimulusjs.org/",
        "cpe": null
    },
    {
        "name": "Fastly",
        "slug": "fastly",
        "categories": [
            {
                "id": 31,
                "slug": "cdn",
                "name": "CDN",
                "priority": 9
            }
        ],
        "confidence": 100,
        "version": "",
        "icon": "Fastly.svg",
        "website": "https://www.fastly.com",
        "cpe": null
    },
    {
        "name": "Gravatar",
        "slug": "gravatar",
        "categories": [
            {
                "id": 19,
                "slug": "miscellaneous",
                "name": "Miscellaneous",
                "priority": 9
            }
        ],
        "confidence": 100,
        "version": "",
        "icon": "Gravatar.png",
        "website": "http://gravatar.com",
        "cpe": null
    },
    {
        "name": "jQuery",
        "slug": "jquery",
        "categories": [
            {
                "id": 59,
                "slug": "javascript-libraries",
                "name": "JavaScript libraries",
                "priority": 9
            }
        ],
        "confidence": 100,
        "version": "",
        "icon": "jQuery.svg",
        "website": "https://jquery.com",
        "cpe": "cpe:/a:jquery:jquery"
    }
]

Wappalyzer results: 
[
  {
    "slug": "google-maps",
    "name": "Google Maps",
    "confidence": 100,
    "version": null,
    "icon": "Google Maps.svg",
    "website": "http://maps.google.com",
    "cpe": null,
    "categories": [
      {
        "id": 35,
        "slug": "maps",
        "name": "Maps"
      }
    ]
  },
  {
    "slug": "varnish",
    "name": "Varnish",
    "confidence": 100,
    "version": null,
    "icon": "Varnish.svg",
    "website": "http://www.varnish-cache.org",
    "cpe": null,
    "categories": [
      {
        "id": 23,
        "slug": "caching",
        "name": "Caching"
      }
    ]
  },
  {
    "slug": "stimulus",
    "name": "Stimulus",
    "confidence": 100,
    "version": null,
    "icon": "Stimulus.png",
    "website": "https://stimulusjs.org/",
    "cpe": null,
    "categories": [
      {
        "id": 12,
        "slug": "javascript-frameworks",
        "name": "JavaScript frameworks"
      }
    ]
  },
  {
    "slug": "fastly",
    "name": "Fastly",
    "confidence": 100,
    "version": null,
    "icon": "Fastly.svg",
    "website": "https://www.fastly.com",
    "cpe": null,
    "categories": [
      {
        "id": 31,
        "slug": "cdn",
        "name": "CDN"
      }
    ]
  },
  {
    "slug": "google-analytics",
    "name": "Google Analytics",
    "confidence": 100,
    "version": null,
    "icon": "Google Analytics.svg",
    "website": "http://google.com/analytics",
    "cpe": null,
    "categories": [
      {
        "id": 10,
        "slug": "analytics",
        "name": "Analytics"
      }
    ]
  },
  {
    "slug": "google-tag-manager",
    "name": "Google Tag Manager",
    "confidence": 100,
    "version": null,
    "icon": "Google Tag Manager.svg",
    "website": "http://www.google.com/tagmanager",
    "cpe": null,
    "categories": [
      {
        "id": 42,
        "slug": "tag-managers",
        "name": "Tag managers"
      }
    ]
  },
  {
    "slug": "jquery",
    "name": "jQuery",
    "confidence": 100,
    "version": "1.12.4",
    "icon": "jQuery.svg",
    "website": "https://jquery.com",
    "cpe": "cpe:/a:jquery:jquery",
    "categories": [
      {
        "id": 59,
        "slug": "javascript-libraries",
        "name": "JavaScript libraries"
      }
    ]
  },
  {
    "slug": "gravatar",
    "name": "Gravatar",
    "confidence": 100,
    "version": null,
    "icon": "Gravatar.png",
    "website": "http://gravatar.com",
    "cpe": null,
    "categories": [
      {
        "id": 19,
        "slug": "miscellaneous",
        "name": "Miscellaneous"
      }
    ]
  },
  {
    "slug": "optimizely",
    "name": "Optimizely",
    "confidence": 100,
    "version": null,
    "icon": "Optimizely.svg",
    "website": "https://www.optimizely.com",
    "cpe": null,
    "categories": [
      {
        "id": 74,
        "slug": "a-b-testing",
        "name": "A/B Testing"
      }
    ]
  },
  {
    "slug": "recaptcha",
    "name": "reCAPTCHA",
    "confidence": 100,
    "version": null,
    "icon": "reCAPTCHA.svg",
    "website": "https://www.google.com/recaptcha/",
    "cpe": null,
    "categories": [
      {
        "id": 16,
        "slug": "security",
        "name": "Security"
      }
    ]
  },
  {
    "slug": "google-adsense",
    "name": "Google AdSense",
    "confidence": 100,
    "version": null,
    "icon": "Google AdSense.svg",
    "website": "https://www.google.fr/adsense/start/",
    "cpe": null,
    "categories": [
      {
        "id": 36,
        "slug": "advertising",
        "name": "Advertising"
      }
    ]
  }
]

**Comment by Kikobeats** [comment]
that is strange – what version are you using?

**Comment by anooj-gandham** [comment]
I am using
"simple-wappalyzer": "^1.1.26"
"html-get": "^2.8.21",

**Comment by Kikobeats** [comment]
can you check if [postinstall](https://github.com/Kikobeats/simple-wappalyzer/blob/master/package.json#L74) is being executed?

**Comment by anooj-gandham** [comment]
Is is not being executed.

**Comment by Kikobeats** [comment]
that's the thing, the post-install fetched wappalyzer db snapshot; try to debug enabling all the logs at npm level
