### ISSUE TITLE
new detections source?

### ISSUE THREAD

**Issue by paulirish** [Kikobeats/simple-wappalyzer#63]
heya dude.   👋  good to see you around again. 

now that the aliasio repo is gone... i guess you've stopped updating right?   

There's a million forks and related efforts but so far I've only found this one that is actively maintaining the detections https://github.com/enthec/webappanalyzer 

have you spotted any others? no big deal either way but if you've sunk hours into the same thing, i'd rather get the scoop from you. :)   cheers

**Comment by Kikobeats** [comment]
Hey Paul!

I didn't know about that fork. Here is another one: https://github.com/Lissy93/wapalyzer.  I'm waiting to see if one of them gets enough traction to decide what to do with this project.

**Comment by sabatale** [comment]
+1 Looks like enthec is making proper updates so far.

**Comment by Kikobeats** [comment]
Using [enthec/webappanalyzer](https://github.com/enthec/webappanalyzer) from now, it seems it's the most active fork.
